MemoApp/Models/Object/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace MemoApp.Models.Object
{
    public class Employee
    {
        [Key]
        public int EmployeeId { get; set; }
        public string? Name { get; set; }
        public int UserId { get; set; }

        public ICollection<EmployeeJob> EmployeeJobs { get; set; }
        public ICollection<MemoEmployee> MemoEmployees { get; set; }
    }
}

MemoApp/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MemoApp.Models.Dto;
using MemoApp.Models.Object;
using MemoApp.Services;

namespace MemoApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly DbService DbService;
        private UserService UserService;

        public EmployeeController(DbService dbContext, UserService userService)
        {
            DbService = dbContext;
            UserService = userService;
        }

        public async Task<IActionResult> Index(int IdEmployee)
        {
            var employee  = DbService.getEmployee(IdEmployee).Result;
            UserService.SetActiveEmployee(employee);
            EmployeeHomePageDto EmployeeData = new EmployeeHomePageDto()
            {
                Name = employee.Name,
                Jobs = DbService.getJobOfEmployee(IdEmployee).Result,
                MemosAssigned = DbService.getMemoAssigned(IdEmployee).Result,
                MemosCreatedCount = DbService.getMemoCreatedCount(employee.Name).Result,
            };
            var model = EmployeeData;
            return View(model);
        }

        public async Task<IActionResult> Disconnect()
        {
            UserService.UnSetActiveEmployee();
            return RedirectToAction("SignIn", "LogIn");
        }
    }
}

MemoApp/Controllers/MemoController.cs
using MemoApp.Models.Object;
using MemoApp.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using MemoApp.Services;
using System.Drawing.Printing;

namespace MemoApp.Controllers
{
    public class MemoController : Controller
    {
        //Access to the services
        private readonly DbService DbService;
        public UserService UserService;

        public MemoController(DbService dbContext, UserService userService)
        {
            DbService = dbContext;
            UserService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int IdMemo)
        {
            var memo = await DbService.getDetailMemo(IdMemo);
            ViewBag.Employee = UserService.GetActiveEmployee(); 
            DetailMemoDto memoDto = new DetailMemoDto()
            {
                MemoId = memo.MemoId,
                Name = memo.Name,
                Description = memo.Description,
                CreationDate = memo.CreationDate,
                CreatedBy = memo.CreatedBy,
                ModificationDate = memo.ModificationDate,
                ModifiedBy = memo.ModifiedBy,
            };
            var model = memoDto;
            return View(model);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int IdMemo)
        {
            var memo = await DbService.getDetailMemo(IdMemo);
            ViewBag.Employee = UserService.GetActiveEmployee();
            EditMemoDto Dto = new EditMemoDto()
            {
                MemoId = memo.MemoId,
                Name = memo.Name,
                Description = memo.Description,
                ModificationDate = memo.ModificationDate,
                ModifiedBy = memo.ModifiedBy,
            };
            return View(Dto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditMemoDto EditedMemo)
        {
            var data = await DbService.getDetailMemo(EditedMemo.MemoId);
            
            if(data != null)
            {
                data.Name = EditedMemo.Name;
                data.Description = EditedMemo.Description;
                data.ModificationDate = DateTime.Now;
                data.ModifiedBy = UserService.GetActiveEmployee().Name;
                await DbService.SaveChanges();
                return RedirectToAction("Index", "Employee", new { IdEmployee = UserService.GetActiveEmployeeId()});
            }
            else
            {
                return View(EditedMemo);
            } 
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Jobs =  await DbService.getJobs();
            ViewBag.Employee = UserService.GetActiveEmployee(); 
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMemoDto CreateMemoDto, IFormFile file) 
        {
            ViewBag.Jobs = await DbService.getJobs();
            ViewBag.Employee = UserService.GetActiveEmployee();
            var lastMemo = await DbService.getLastMemo();
            int LastId = lastMemo.MemoId;
            Memo data = new Memo()
            {
                //MemoId = LastId + 1,
                Name = CreateMemoDto.Name,
                Description = CreateMemoDto.Description,
                CreationDate = DateTime.Now,
                CreatedBy = UserService.GetActiveEmployee().Name,
                ModificationDate = null,
                ModifiedBy = null
            };
            await DbService.AddMemo(data);

            await DbService.SaveChanges();

            await CreateMemoJob(data.MemoId, CreateMemoDto.JobsId);

            if (file != null && file.ContentType == "application/pdf")
            {
                await UploadFile(file, data.Name, CreateMemoDto.JobsId);
                return RedirectToAction("Index", "Employee", new { IdEmployee = UserService.GetActiveEmployeeId() });
            }

            return View(CreateMemoDto);
        }

        public async Task CreateMemoJob(int MemoId, List<int> JobsId)
        {
            Console.WriteLine("******************Before MemoJobs creation**************************");
            foreach(var Id in JobsId)
            {
                await DbService.CreateMemoJob(MemoId, Id);
            }
            Console.WriteLine("*******************MemosJobs Created***************************");
            await DbService.SaveChanges();
            Console.WriteLine("************************MemoJobs save**************************");
            await CreateMemoEmployee(MemoId, JobsId);
        }

        public async Task CreateMemoEmployee(int MemoId, List<int> JobsId)
        {
            Console.WriteLine("************************before MemoEmploye creation**************************");
            foreach (var Id in JobsId)
            {
                var EmployeesId = await DbService.getEmployeesIdFromJobId(Id);
                foreach(var EmployeeId in EmployeesId)
                {
                    await DbService.CreateMemoEmployee(MemoId, EmployeeId);
                }
            }
            Console.WriteLine("************************after MemoEmploye creation**************************");
            await DbService.SaveChanges();
            Console.WriteLine("************************after MemoEmploye save**************************");

        }

        public async Task UploadFile(IFormFile file, string NameMemo, List<int> JobId)
        {
            string MainDirectory = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot", "UploadedFile");
            //If main directory doesnt exist create it
            if(!Directory.Exists(MainDirectory))
            {
                Directory.CreateDirectory(MainDirectory);
            }
            //If the directory for each jobId doesnt exist create it
            //Change the name of the file for the memo name and add the file in each directory.
            foreach (var id in JobId)
            {
                string JobDirectory = Path.Combine(MainDirectory, id.ToString());
                if(!Directory.Exists(JobDirectory))
                {
                    Directory.CreateDirectory(JobDirectory);
                }
                var FilePath = Path.Combine(JobDirectory, NameMemo);
                //Upload it via stream
                using (FileStream stream = new FileStream(FilePath, FileMode.Create))
                {
                   
                    await file.CopyToAsync(stream);
                }
            }
        }
    }
}

MemoApp/Controllers/MemoEmployeeController.cs
using MemoApp.Models.Dto;
using MemoApp.Services;
using Microsoft.AspNetCore.Mvc;


namespace MemoApp.Controllers
{
    public class MemoEmployeeController : Controller
    {
        //Access to the services
        private readonly DbService DbService;
        public UserService UserService;

        public MemoEmployeeController(DbService dbContext, UserService userService)
        {
            DbService = dbContext;
            UserService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Signing(int IdMemo)
        {
            var employee = UserService.GetActiveEmployee();
            ViewBag.Employee = employee;
            var memo = DbService.getDetailMemo(IdMemo).Result;
            var memoEmployee = DbService.getMemoEmployee(IdMemo, employee.EmployeeId).Result;

            MemoEmployeeDto memoEmployeeDto = new MemoEmployeeDto()
            { 
                MemoId = IdMemo,
                Name = memo.Name,
                Description = memo.Description,
                CreatedBy = memo.CreatedBy,
                Signed = memoEmployee.Signed,
            };
            var model = memoEmployeeDto;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Signing(MemoEmployeeDto model, string password)
        {
            var employee = UserService.GetActiveEmployee();
            ViewBag.Employee = employee;
            //Verifier le mot de passe entrer si correcte indiquer succes et retourner menu principal
            //Si incorrecte indiquer erreur et View()
            if (string.IsNullOrEmpty(password))
            {
                ModelState.AddModelError("", "Passwword cannot be empty.");
                return View(model);
            }
            else
            {
                var user = DbService.GetUser(employee.EmployeeId);
                if (password == user.Result.Password)
                {
                    DbService.SignMemoEmployee(model.MemoId, employee.EmployeeId);
                    return RedirectToAction("Index", "Employee", new { IdEmployee = employee.EmployeeId });
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect password, please try again.");
                    return View(model);
                }
            }
        }
    }
}

MemoApp/Views/Employee/Index.cshtml
@using MemoApp.Models.Dto;
@model EmployeeHomePageDto;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Welcome back @Model.Name</h1>

<div class="container">
    <div class="card table">
        <div class="card-header">
            <h5>Assigned</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table md-0">
                    <thead class="small text-uppercase bg-body text-muted">
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Created by</th>
                            <th>Creation date</th>
                            <th>Signed</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if(Model.MemosAssigned == null)
                            {
                                <p>No memo assigned to you.</p>
                            }
                            else
                            {
                                foreach (var memo in Model.MemosAssigned)
                                {
                                    if(memo.Signed == true)
                                    {
                                        <tr class="align-midle bg-success">
                                            <td>

                                            </td>
                                            <td>@memo.Name</td>
                                            <td>@memo.CreatedBy</td>
                                            <td>@memo.CreationDate</td>
                                            <td>true</td>
                                        </tr>
                                    }
                                    else
                                    {
                                        <tr class="align-midle bg-danger">
                                            <td>
                                                <a class="icon-link" onclick="location.href='@Url.Action("Signing", "MemoEmployee", new { IdMemo = memo.MemoId })'">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0" />
                                                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7" />
                                                    </svg>
                                                </a>
                                            </td>
                                            <td>@memo.Name</td>
                                            <td>@memo.CreatedBy</td>
                                            <td>@memo.CreationDate</td>
                                            <td>false</td>
                                        </tr>
                                    }

                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="card table">
        <div class="card-header">
            <h5>Created</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table md-0">
                    <thead class="small text-uppercase bg-body text-muted">
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Name</th>
                            <th>Creation date</th>
                            <th>Modified by</th>
                            <th>Modification date</th>
                            <th>Assignation count</th>
                            <th>Signed count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            if(Model.MemosCreatedCount == null)
                            {
                                <p>No memo created.</p>
                            }
                            else
                            {
                                foreach (var memo in Model.MemosCreatedCount)
                                {
                                    <tr class="align-midle">
                                        <td>
                                            <a class="icon-link" onclick="location.href='@Url.Action("Detail", "Memo", new { IdMemo = memo.MemoId })'">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
                                                    <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a2 2 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139q.323-.119.684-.12h5.396z" />
                                                </svg>
                                            </a>
                                        </td>
                                        <td>
                                            <a class="icon-link" onclick="location.href='@Url.Action("Edit", "Memo", new { IdMemo = memo.MemoId })'">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325" />
                                                </svg>
                                            </a>
                                        </td>
                                        <td>@memo.Name</td>
                                        <td>@memo.CreationDate</td>
                                        @if (memo.ModifiedBy == null)
                                        {
                                            <td>No modification</td>
                                        }
                                        else
                                        {
                                            <td>@memo.ModifiedBy</td>
                                        }
                                        @if (memo.ModificationDate == null)
                                        {
                                            <td>No modification</td>
                                        }
                                        else
                                        {
                                            <td>@memo.ModificationDate</td>
                                        }
                                        <td>@memo.TotalAssigned</td>
                                        <td>@memo.ReadAssigned</td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Create","Memo")'">Create memo</button>
    <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Disconnect", "Employee")'">Disconnect</button>
</div>